### PR TITLE
Created TestSuite in order to perform all the tests in one go

### PR DESCRIPTION
**Pull request by jorgeejgonzalez**

### CODE REVIEW

**Comment by rmannibucau** [comment]
Not sure i get the point. Surefire does it well and we dont need to maintain a list of tests.

**Comment by jorgeejgonzalez** [comment]
I use it to run all tests in the base test package from inside the IDE (currently using Eclipse Luna), this I do mostly for safe refactoring and allows me to view the execution with the JUnit eclipse plugin

**Comment by rmannibucau** [comment]
AFAIK IDE allow to do it without suite classes

**Comment by jorgeejgonzalez** [comment]
you're absolutely right, my bad

**Pull request closed without merging**
