### PR TITLE
Cukedoctor integration

### PR DESCRIPTION
**Pull request by rmpestano**
This PR refers to issue #53.

Basically created two config attributes into CucumberConfiguration, **generateDocs** and **docsDirectory** (defaults to/target/docs). 

If generateDocs is set to true then Cukedoctor will be activated on [doReport method](https://github.com/rmpestano/cukespace/blob/master/core/src/main/java/cucumber/runtime/arquillian/reporter/CucumberReporter.java#L80). 

Note that it depends on AsciidocrJ and asciidoctorJ-pdf.

### CODE REVIEW

**Comment by rmannibucau** [comment]
Hi very interesting, I have however few config questions:

- shouldnt then the default doc deactivable? (ie noenrichment + no rendering)
- same for adoc part for enrichment
- i d like to beable to generate the adoc but not the htmland/or pdf which could be done through a custom setup of mvn plugin for instance for advanced cases (easier for custom themes)

wdyt?

**Comment by rmpestano** [comment]
Hi,

"shouldnt then the default doc deactivable? (ie noenrichment + no rendering)" 

what you mean by default doc? 

"same for adoc part for enrichment" you mean [here](https://github.com/rmpestano/cukespace/blob/master/core/src/main/java/cucumber/runtime/arquillian/reporter/CucumberReporter.java#L94)? 

"i d like to beable to generate the adoc but not the htmland/or pdf which could be done through a custom setup of mvn plugin for instance for advanced cases (easier for custom themes)"

I agree but you mean only document attributes enhancements or also document structure (eg: dont render summary table) ?

for document attributes I just pushed to master the possibility to not render docAtributes, [see here](https://github.com/rmpestano/cukedoctor/issues/18) for details.

Also like the idea to use the maven plugin, its more flexible.  

thanks for your considerations.

**Comment by rmannibucau** [comment]
Hi,

We support the same as jenkins html rendering so both should be configurable separately. Wonder if we should inteoduce a new extension config named cukespace-reporting-adoc.


If you dont need anything on server side ignore enrichment question.

About final rendering I d support a config "types" with a csv value containing by default just adoc but supporting adoc,html,pdf.

Aldo attributes should be customizables. Using a multiple properties syntax should be fine:

<property name="attributes-default">
Attr=val
Other=alternate
...
</property>

**Comment by rmpestano** [comment]
In last commit I removed Asciidoctor dependency so i'm just generating adoc file with Cukedoctor and configuring and generating final document with maven plugin.

 Now pdf backend is working but one issue we have now is that when a test fails the documentation is not generated (next maven phase is not invoked).

**Comment by rmannibucau** [comment]
It is fine and better to have it by default but users should be able to generate their own adoc. Was just my point.

Ill take some time tonight to try to review more and merge.

**Comment by rmpestano** [comment]
Alright, for now both approaches are in the PR:
  - asciidoc maven plugin 
  - cukespace default  docs generated at docs dir

**Comment by rmannibucau** [comment]
ok,

I'm happy with the impl but not yet with the conf.

    <property name="report">true</property>
    <property name="generateDocs">true</property>

report is the same as generateDocs for me. I'd deprecate all the report config with have now (ie in last release) and move it over some dedicated blocks.


Ie:

      <extension qualifier="cucumber-report-default"> 
        
        <property name="directory">target/cucumber-report</property>
      </extension>
      <extension qualifier="cucumber-report-adoc">
        <property name="directory">target/cucumber-report-adoc</property>
        <property name="directory-html">target/cucumber-report-html</property> 
        <property name="directory-pdf">target/cucumber-report-pdf</property>
        <property name="formats">adoc,html,pdf</property>
        <property name="attributes"> 
            linkcss =
            custom-attr = custom-val
        </property>
        <property name="attributes-html">
            imagesdir = img/
        </property>
        <property name="attributes-pdf">
            themedir = foo
        </property>
      </extension>

wdyt?

**Comment by rmpestano** [comment]
That's nice. Do you think using yaml for doc config is too cumbersome? somethink like:

  <extension qualifier="cucumber-report-adoc">
    <property name="docsConfig"> 
       directory: target/cucumber-report-adoc
       formats: pdf, html, adoc
       attributes:  
           linkcss: true
           custom-attr = custom-val
       attributes-html:
          directory-html: target/cucumber-report-html  
           toc: right
           imagesdir = img/   
       attributes-pdf: 
          themedir = foo
    </property>
  </extension>

we could provide a custom docsConfig.yml file and also could map it that to java objects instead of parsing strings.

what do you think?

**Comment by rmannibucau** [comment]
If you want a config file as option ok but id like it in arq.xml by default

**Comment by rmpestano** [comment]
no problem, I'll keep with the xml config and later we see if a config file is necessary

**Comment by rmannibucau** [comment]
Do you want to have a try with the proposed config before I merge?

**Comment by rmpestano** [comment]
I think you can merge and we create an issue to improve reports config, WDYT?

**Pull request merged**
